name: CI

on: [push]

jobs:
  debian-example-image:
    name: Debian example image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: ./kas-container build kas-iot2050-example.yml
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-example-image
          path: |
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic.img
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic.img.bmap

  debian-rt-example-image:
    name: Debian RT example image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: ./kas-container build kas-iot2050-example.yml:kas/opt/preempt-rt.yml
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-example-image-rt
          path: |
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic.img
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic.img.bmap

  bootloaders:
    name: Bootloaders for both PG1 and PG2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build bootloader image for PG1
        run: ./kas-container build kas-iot2050-boot-pg1.yml
      - name: Build bootloader image for PG2
        run: ./kas-container build kas-iot2050-boot-pg2.yml
      - name: Archive bootloaders
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-bootloaders
          path: build/tmp/deploy/images/iot2050/*.bin
  
  download_bootloaders:
    needs: bootloaders
    runs-on: [self-hosted, Linux_527]
    steps:
        - name: download_bootloader
          run: echo "download"
        - uses: actions/download-artifact@v2
          with:
            name: iot2050-bootloaders
            path: $GITHUB_RUN_NUMBER/download
            
  download_debian-example-image:
    needs: debian-example-image
    runs-on: [self-hosted, Linux_527]
    steps:
        - name: download_debian-example-image
          run: echo "download"
        - uses: actions/download-artifact@v2
          with:
            name: iot2050-example-image
            path: $GITHUB_RUN_NUMBER/download

  download_debian-rt-example-image:
    needs: debian-rt-example-image
    runs-on: [self-hosted, Linux_527]
    steps:
        - name: download_debian-rt-example-image
          run: echo "download"
        - uses: actions/download-artifact@v2
          with:
            name: iot2050-example-image-rt
            path: $GITHUB_RUN_NUMBER/download
